### PR TITLE
Create RegisterForm.html

### PR DESCRIPTION
**Pull request by varunsharma6956**

### CODE REVIEW

**Comment by sandeep-ahirwar** [comment]
@varunsharma6956 can u share screenshot?

**Comment by varunsharma6956** [comment]
Screenshot (1138)

**Comment by varunsharma6956** [comment]
Hey sir shared screenshot of which form I created can you merge it and
approve it

**Comment by varunsharma6956** [comment]
Sir I made registration form using html with inline css in it can you
approve pr and merge it

**Comment by varunsharma6956** [comment]
shared screenshot sir

**Review by sandeep-ahirwar — COMMENTED** [review]
Can do better that this!

**Comment by varunsharma6956** [comment]
Ok sir I will do more better than this with more changes if possible merge this

**Pull request closed without merging**
