### PR TITLE
added flipkart clone

### PR DESCRIPTION
**Pull request by sumanparajuli**

### CODE REVIEW

**Review by sandeep-ahirwar — APPROVED** [review]
It's good, Can you work on it's backend?

**Comment by sumanparajuli** [comment]
Sir. I have started learning backend recently. That's why i am unable to work on it's backend currently. I know frontend only at this point of time. Hope you'll understand.

**Comment by sandeep-ahirwar** [comment]
@sumanparajuli  no problem, you can work on more clones.

**Comment by sumanparajuli** [comment]
for sure sir !

**Pull request merged**
